
ExpenseType.create(tag: "food")
ExpenseType.create(tag: "pharmacy")
ExpenseType.create(tag: "furniture")
ExpenseType.create(tag: "Automotive")
ExpenseType.create(tag: "Electronics")
ExpenseType.create(tag: "Entertainment")
ExpenseType.create(tag: "Gifts")
ExpenseType.create(tag: "Health")
ExpenseType.create(tag: "Beauty")
ExpenseType.create(tag: "Clothes")
ExpenseType.create(tag: "Restaurants")
ExpenseType.create(tag: "other")